### PR TITLE
Bound temperature

### LINKED ISSUE #135: base_policy to_yaml fails
When running no preprocessor, everything seems to work.

I created a preprocessor, that is almost the same as your convnet preprocessor. I cannot test your convnet preprocessor directly, because I have no image environment.

to_yaml gives following error message, but i have no idea, what the weakref object could be...

2020-04-06 13:59:29,554	ERROR trial_runner.py:538 -- Trial id=00000-seed=2976: Error processing result.
Traceback (most recent call last):
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 536, in _process_trial_save
    checkpoint_value = self.trial_executor.fetch_result(trial)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 381, in fetch_result
    result = ray.get(trial_future[0], DEFAULT_GET_TIMEOUT)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/ray/worker.py", line 1513, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(TypeError): ray::ExperimentRunner.save() (pid=13928, ip=192.168.0.141)
  File "python/ray/_raylet.pyx", line 452, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 407, in ray._raylet.execute_task.function_executor
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/ray/tune/trainable.py", line 342, in save
    checkpoint = self._save(checkpoint_dir)
  File "/home/manuel/Code/translearn/softlearning_new/examples/development/main.py", line 238, in _save
    self._save_policy(checkpoint_dir)
  File "/home/manuel/Code/translearn/softlearning_new/examples/development/main.py", line 180, in _save_policy
    self.policy.save(save_path)
  File "/home/manuel/Code/translearn/softlearning_new/softlearning/policies/base_policy.py", line 229, in save
    config_yaml = self.to_yaml()
  File "/home/manuel/Code/translearn/softlearning_new/softlearning/policies/base_policy.py", line 221, in to_yaml
    yaml.dump(self._updated_config(), **kwargs)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/yaml/__init__.py", line 290, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/yaml/__init__.py", line 278, in dump_all
    dumper.represent(data)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/yaml/representer.py", line 27, in represent
    node = self.represent_data(data)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/yaml/representer.py", line 48, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/yaml/representer.py", line 207, in represent_dict
    return self.represent_mapping('tag:yaml.org,2002:map', data)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/yaml/representer.py", line 118, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/yaml/representer.py", line 48, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/yaml/representer.py", line 207, in represent_dict
    return self.represent_mapping('tag:yaml.org,2002:map', data)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/yaml/representer.py", line 118, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/yaml/representer.py", line 48, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/yaml/representer.py", line 364, in represent_ordered_dict
    return self.represent_sequence(tag, [items])
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/yaml/representer.py", line 92, in represent_sequence
    node_item = self.represent_data(item)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/yaml/representer.py", line 48, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/yaml/representer.py", line 199, in represent_list
    return self.represent_sequence('tag:yaml.org,2002:seq', data)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/yaml/representer.py", line 92, in represent_sequence
    node_item = self.represent_data(item)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/yaml/representer.py", line 48, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/yaml/representer.py", line 199, in represent_list
    return self.represent_sequence('tag:yaml.org,2002:seq', data)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/yaml/representer.py", line 92, in represent_sequence
    node_item = self.represent_data(item)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/yaml/representer.py", line 52, in represent_data
    node = self.yaml_multi_representers[data_type](self, data)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/yaml/representer.py", line 343, in represent_object
    'tag:yaml.org,2002:python/object:'+function_name, state)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/yaml/representer.py", line 118, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/yaml/representer.py", line 52, in represent_data
    node = self.yaml_multi_representers[data_type](self, data)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/yaml/representer.py", line 343, in represent_object
    'tag:yaml.org,2002:python/object:'+function_name, state)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/yaml/representer.py", line 118, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/yaml/representer.py", line 48, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/yaml/representer.py", line 207, in represent_dict
    return self.represent_mapping('tag:yaml.org,2002:map', data)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/yaml/representer.py", line 117, in represent_mapping
    node_key = self.represent_data(item_key)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/yaml/representer.py", line 52, in represent_data
    node = self.yaml_multi_representers[data_type](self, data)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/yaml/representer.py", line 317, in represent_object
    reduce = data.__reduce_ex__(2)
TypeError: can't pickle weakref objects
2020-04-06 13:59:29,561	INFO trial_runner.py:636 -- Trial id=00000-seed=2976: Attempting to restore trial state from last checkpoint.

### PR DESCRIPTION
**Pull request by hartikainen**
This should fix #135, #136, and #141. Still need to verify the performance on the standard benchmarks before this can be merged.

### CODE REVIEW

**Comment by externalhardrive** [comment]
Should this line https://github.com/hartikainen/softlearning/blob/dc42e7a06ea047bfe7824cdf44de8087071f1306/softlearning/algorithms/sac.py#L322
be `'_log_alpha': self._log_alpha,` or does it automatically see that self._alpha depend on self._log_alpha and saves it also?

**Comment by hartikainen** [comment]
@externalhardrive good call. Need to make sure the serializations still work before merging.

**Comment by hartikainen** [comment]
## Results from dc42e7a:

### `Hopper-v3`:
image

### `Walker2d-v3`:
image

### `HalfCheetah-v3`:
image

### `Ant-v3`:
image

**Comment by hartikainen** [comment]
These `tf.nn.compute_average_loss` calls effectively change the learning rate of Q and policy. I don't see much difference in the performance compared to the latest master, and averaging is in line with the way we used to do things before tf2 changes, so I'm gonna leave the learning rates as is. I think we should sweep over them again at some point.

**Pull request merged**
